[package]
name = "coin_machine_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsfsm_proc = { path = "../rsfsm_proc" }
expand = "0.3.0"
